name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install DNS Utils
      run: sudo apt install dnsutils -y
    - name: remove Bind 9
      run: sudo apt purge bind9 -y
    - name: Run DNS Service
      run: sudo nohup dotnet run &
    - name: Do DNS Dig
      run: dig @127.0.0.1 test.com A +noedns +notcp

